version: '3.3'
services:
    web:
        build: .
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - back

networks:
    back:
        driver: bridge
