version: '3.3'
services:
    db:
        image: paulosteffenm/book-app:latest
        restart: always
        expose:
            - '80:80'
        networks:
            - back

networks:
    back:
        driver: bridge
