version: '3.3'
services:
    book-app:
        image: paulosteffenm/book-app:latest
        restart: always
        ports:
            - '80:80'
        networks:
            - back

networks:
    back:
        driver: bridge
